### ISSUE TITLE
Configuration warning - unrecognized property "routeSettings"

### ISSUE THREAD

**Issue by mileswatson** [talbotp/serverless-apigateway-route-settings#2]
When packaging or deploying, Serverless displays the following warning:

`Configuration warning at 'functions.demofunction.events[0].httpApi': unrecognized property 'routeSettings'`.

According to this [page](https://www.serverless.com/framework/docs/configuration-validation/), the extension needs to extend the validation schema, in order to remove the warning and improve robustness.

**Comment by talbotp** [comment]
@mileswatson That's super helpful :+1: , thanks, wasn't aware of this :slightly_smiling_face:

**Comment by talbotp** [comment]
This is solved in commit [b8481c4e86985a11beacc8f24faa4fb5dbad7f15](https://github.com/talbotp/serverless-apigateway-route-settings/commit/b8481c4e86985a11beacc8f24faa4fb5dbad7f15), and released into version [0.0.6](https://www.npmjs.com/package/serverless-apigateway-route-settings/v/0.0.6). 

Thanks for noticing this bug :slightly_smiling_face:
