### ISSUE TITLE
setup with serverless-express

### ISSUE THREAD

**Issue by madruga8** [talbotp/serverless-apigateway-route-settings#7]
I'm trying to replace the default sam-template from @vendia/serverless-express v2 example.

https://github.com/vendia/serverless-express/tree/mainline/examples/basic-starter-api-gateway-v2 

How the serverless.yml will need to look like to deploy this httpApi example ?

Thank you very much.

**Comment by talbotp** [comment]
Hi @madruga8 

This is an extensive example of a serverless.yml which i find really useful to compare against when making a serverless.yml : [Example](https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/). It has a lot of excess info for a httpApi, but is still useful.

[Here's](https://github.com/talbotp/wonkywheel/blob/master/api/serverless.yml) a small serverless.yml i made for a small project you can look at. It will be missing some stuff that is in the SAM-template like resources for Route 53 and Certificate Manager etc, I think you can use [this](https://www.serverless.com/plugins/serverless-certificate-creator) plugin to get started with domain related stuff.

Cheers 🙂
