### ISSUE TITLE
Not compatible with serverless v3

### ISSUE THREAD

**Issue by shopsideau** [talbotp/serverless-apigateway-route-settings#8]
Any chance of us getting an update so this plugin works with the new serverless v3?

Would be greatly appreciated!

**Comment by talbotp** [comment]
Hey
I will take a look at this. I am less busy from the 14th onward so will likely fix it then :) 
Thanks!

**Comment by shopsideau** [comment]
Sounds good, thanks so much!

**Comment by talbotp** [comment]
Hi @shopsideau 

This has been fixed and deployed to npm with version 1.1.0 :+1: 

For some reason serverless v3 expected the validationSchema to be formatted a bit differently. :smile:
